services:
  postgres:
    image: postgres:14
    container_name: postgres_nominatim
    restart: always
    shm_size: '1gb'
    environment:
      POSTGRES_DB: nominatim
      POSTGRES_USER: nominatim
      POSTGRES_PASSWORD: MatusZaida180467
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  nominatim:
    image: mediagis/nominatim:4.2
    container_name: nominatim
    restart: always
    depends_on:
      - postgres
    environment:
      PBF_PATH: /data/region.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/europe/spain/cataluna-updates
      NOMINATIM_PASSWORD: MatusZaida180467      
    volumes:
      - ./cataluna-latest.osm.pbf:/data/region.osm.pbf:ro
      - nominatim_data:/var/lib/postgresql/14/main
    command: bash /app/start.sh

  osrm_backend:
    image: osrm/osrm-backend:latest
    container_name: osrm_backend
    restart: always
    volumes:
      - osrm_data:/data
    command: "osrm-routed --algorithm mld /data/map.osrm"

  webapp:
    build:
      context: .
    container_name: holabarrio_dev
    restart: always
    env_file:
      - ./.env
    depends_on:
      - postgres
    
  nginx_proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot_www:/var/www/certbot/:ro
      - certbot_conf:/etc/letsencrypt/:ro
    depends_on:
      - webapp
      - osrm_backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot_www:/var/www/certbot/:rw
      - certbot_conf:/etc/letsencrypt/:rw

volumes:
  postgres_data:
  nominatim_data:
  osrm_data:
  certbot_www:
  certbot_conf:

