# Nombre del workflow
name: Deploy to VPS

# Disparador: se activa cuando subes código a la rama 'main'
on:
  push:
    branches:
      - main

# Trabajos a ejecutar
jobs:
  deploy:
    # El tipo de máquina virtual donde se ejecutará el workflow
    runs-on: ubuntu-latest

    # Pasos del trabajo
    steps:
      # Paso 1: Descarga tu código del repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Ejecuta los comandos en tu VPS por SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          timeout: 30m
          script: |
            set -e
            # Navega a la carpeta principal del proyecto Docker en el VPS
            cd ~/osrm_project
            
            # Entra en la carpeta de la app, actualiza el código y vuelve
            cd holabarrio
            git pull origin main
            cd ..
            echo "DATABASE_URL_AUTH=${{ secrets.DATABASE_URL_AUTH }}" > ./holabarrio/.env
            echo "DATABASE_URL_APP=${{ secrets.DATABASE_URL_APP }}" >> ./holabarrio/.env
            echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> ./holabarrio/.env
            echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> ./holabarrio/.env
            echo "GITHUB_CLIENT_ID=${{ secrets.GITHUB_CLIENT_ID }}" >> ./holabarrio/.env
            echo "GITHUB_CLIENT_SECRET=${{ secrets.GITHUB_CLIENT_SECRET }}" >> ./holabarrio/.env
            echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> ./holabarrio/.env


            # Detiene los contenedores actuales
            docker compose down
            
            # Reconstruye (si hay cambios) y levanta todos los servicios
            docker compose up --build -d
            
            # (Opcional) Pausa para que los servicios se estabilicen
            echo "Esperando 10 segundos..."
            sleep 10

            # Limpia imágenes de Docker que ya no se usan
            docker image prune -f