name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          timeout: 30m
          script: |
            set -e
            cd ~/osrm_project/holabarrio
            
            git pull origin main
            
            echo "DATABASE_URL_AUTH=${{ secrets.DATABASE_URL_AUTH }}" > ./.env
            echo "DATABASE_URL_APP=${{ secrets.DATABASE_URL_APP }}" >> ./.env
            echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> ./.env
            echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> ./.env
            echo "GITHUB_CLIENT_ID=${{ secrets.GITHUB_CLIENT_ID }}" >> ./.env
            echo "GITHUB_CLIENT_SECRET=${{ secrets.GITHUB_CLIENT_SECRET }}" >> ./.env
            echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> ./.env
            echo "NEXTAUTH_URL=https://holabarrio.es" >> ./.env
            
            docker compose down --remove-orphans
            docker compose up --build -d
            
            docker image prune -f